#!/usr/bin/env python


import argparse
import logging
import coalFLUT

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog='runCoalFLUT',
        description=('Generate a multi-dimensional FLUT for'
                     ' coal combustion based on non-premixed flamelet')
    )
    parser.add_argument('yml', action='store',
                        default=None, help="YML input file")
    parser.add_argument('-n', dest='n_p', action='store',
                        default=1, type=int, help='Number of processors')
    parser.add_argument('--hdf5', dest='hdf5',
                        action='store_true',
                        help=(
                            'Read the existing sldf.h5 file,'
                            ' previously created'))
    parser.add_argument('-d', dest='debug',
                        action='store_true',
                        help='Activate debug messages')
    parser.add_argument('--run-only', dest='run_only',
                        action='store_true',
                        help='Run only ULF and agrregate solutions')
    parser.add_argument('--readfiles', dest='readfiles',
                        action='store_true',
                        help='Read existing files')
    parser.add_argument('--fc', dest='flamelet_config', type=str,
                        action='store',
                        default=None, help='Export to flameletConfig')
    parser.add_argument('-t', dest='turbulent', action='store_true',
                        help='Create table for turbulent flows')
    argument = parser.parse_args()

    n_p = argument.n_p
    flamelet_config = argument.flamelet_config
    logger = logging.getLogger('main')

    if argument.debug:
        logger.setLevel(logging.DEBUG)
    else:
        logger.setLevel(logging.INFO)

    logger.debug('flamelet_config %s', flamelet_config)
    logger.debug('Initialize flut object')
    flut = coalFLUT.CoalFLUT(argument.yml)
    flut_file = flut.basename + '.h5'
    if argument.readfiles:
        logger.debug('Read existing files')
        flut.read_files()
    elif argument.hdf5:
        logger.debug('Read previous hdf5 %s', flut_file)
        flut.read_bin(flut_file)
    else:
        logger.debug('Run ULF')
        flut.run(n_p=argument.n_p)
    logger.debug('Results: %s', flut.__str__())
    flut.squeeze()
    logger.debug('Results after squeezing: %s', flut.__str__())
    if not argument.hdf5:
        logger.debug('Write h5 file %s', flut_file)
        flut.write_bin(flut_file)
    else:
        logger.debug('Don\'t write h5 file')

    # process table
    if not argument.run_only:
        # calc progress variable
        logger.debug('Calc progress variable %s', flut.pv_definition)
        flut.calc_progress_variable()
        logger.debug('Add missing properties')
        flut.add_missing_properties(verbose=True)
        if flamelet_config:
            logger.debug('Export data to HDF5 flamelet_config %s',
                         flamelet_config)
            flut.write_hdf5(file_name=flamelet_config,
                            turbulent=argument.turbulent, n_proc=n_p)
